# Generated by Django 3.1.4 on 2020-12-26 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_userbio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userbio',
            old_name='first_name',
            new_name='f_name',
        ),
        migrations.RenameField(
            model_name='userbio',
            old_name='last_name',
            new_name='l_name',
        ),
    ]
